package ru.sharadze.Passages;


/**
* ru/sharadze/Passages/BackupPathesStringsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Passages.idl
* 24 апреля 2018 г. 16:28:23 MSK
*/

public final class BackupPathesStringsHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public BackupPathesStringsHolder ()
  {
  }

  public BackupPathesStringsHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BackupPathesStringsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BackupPathesStringsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BackupPathesStringsHelper.type ();
  }

}
