package ru.sharadze.Passages;


/**
* ru/sharadze/Passages/BorderType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Passages.idl
* 24 апреля 2018 г. 16:28:23 MSK
*/

public class BorderType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static BorderType[] __array = new BorderType [__size];

  public static final int _TOP = 0;
  public static final BorderType TOP = new BorderType(_TOP);
  public static final int _LEFT = 1;
  public static final BorderType LEFT = new BorderType(_LEFT);
  public static final int _BOTTOM = 2;
  public static final BorderType BOTTOM = new BorderType(_BOTTOM);
  public static final int _RIGHT = 3;
  public static final BorderType RIGHT = new BorderType(_RIGHT);

  public int value ()
  {
    return __value;
  }

  public static BorderType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected BorderType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class BorderType
