package ru.sharadze.Passages;


/**
* ru/sharadze/Passages/BorderTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Passages.idl
* 24 апреля 2018 г. 16:28:23 MSK
*/

abstract public class BorderTypeHelper
{
  private static String  _id = "IDL:Passages/BorderType:1.0";

  public static void insert (org.omg.CORBA.Any a, BorderType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BorderType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (BorderTypeHelper.id (), "BorderType", new String[] { "TOP", "LEFT", "BOTTOM", "RIGHT"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BorderType read (org.omg.CORBA.portable.InputStream istream)
  {
    return BorderType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BorderType value)
  {
    ostream.write_long (value.value ());
  }

}
