package ru.sharadze.Passages;

/**
* ru/sharadze/Passages/BorderTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Passages.idl
* 24 апреля 2018 г. 16:28:23 MSK
*/

public final class BorderTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public BorderType value = null;

  public BorderTypeHolder ()
  {
  }

  public BorderTypeHolder (BorderType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BorderTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BorderTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BorderTypeHelper.type ();
  }

}
