package ru.sharadze.Passages;


/**
* ru/sharadze/Passages/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Passages.idl
* 24 апреля 2018 г. 16:28:23 MSK
*/

public interface GameOperations 
{
  String startGame(String id);
  int onlineCount(String gameId);
  int[] get(String gameId);
  boolean isMyTurn(String id, String gameId);
  boolean addBorder(int x, int y, BorderType type, String id, String gameId);
} // interface GameOperations
